name: Linux conan packages

on: [workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: booritas/slideio-manylinux_2_28_x86_64:v3.0.0
      env:
        CONAN_REVISIONS_ENABLED: 1

    steps:
    - name: Install conan
      run: python3 -m pip install -U conan==1.65.0

    - name: Add conan server
      run: |
        conan remote add slideio ${{ secrets.CONAN_SERVER }}
        conan user -r slideio -p ${{ secrets.CONAN_PASSWORD }} ${{ secrets.CONAN_USER }}

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: install dependencies
      shell: bash  -el {0}
      run: |
        alias python='python3'
        python3 install.py -a conan -c release
        conan upload "*" -r slideio --all -c