name: Linux Wheels

on: [workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: booritas/slideio-py:v2.7.0
      env:
        CONAN_REVISIONS_ENABLED: 1

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: install dependencies
      shell: bash  -el {0}
      run: |
        python3 install.py -a conan -c release

    - name: build wheels
      shell: bash  -el {0}
      run: |
        ./build-wheels-manylinux.sh
  
    - uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: ./wheelhouse
  