name: Build Macos Conan

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-14]

    steps:
  
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        auto-activate-base: true
        activate-environment: "py311"
        
    - name: Create and activate conda environments
      run: |
        conda activate py311
        python --version
        python -m pip install conan==1.65.0
        conan remote add digitalo ${{ secrets.CONAN_SERVER }}
        conan user -r digitalo -p ${{ secrets.CONAN_PASSWORD }} -l ${{ secrets.CONAN_USER }}

    - name: install dependencies
      run: |
        python install.py -a conan -c release
        conan upload "*" -r digitalo --all -c