name: Windows test

on: [workflow_dispatch]
env:
  CONAN_REVISIONS_ENABLED: 1
  CONAN_DISABLE_CHECK_COMPILER: 1
jobs:
  build-mac-win:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
          
    - name: display cmake version
      run: cmake --version
  
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
      
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: ""

    - name: Create and activate conda environments
      run: |
        conda create -n py${{ matrix.python-version }} python=${{ matrix.python-version }} -y
        conda activate py${{ matrix.python-version }}
        python --version

    - name: Run tests for Python ${{ matrix.python-version }}
      run: |
        conda activate py${{ matrix.python-version }}

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.65.0
  
    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"
    
    - name: Add digital ocean conan remote
      run: |
          conan remote add digitalo http://167.172.176.224
  